### ISSUE TITLE
Saving graph on windows crashes application

### ISSUE THREAD

**Issue by tvandergeer** [virinext/pipeviz#3]
When I build a graph and choose 
1. File -> Save
2. type a file name
3. click the Save button
the application quits unexpectedly (crashes).

The file is created but it's empty.

I'm running 1.5.060615 of pipeviz on Windows using [this release](https://github.com/virinext/pipeviz/releases/tag/0.1.5.060615).

**Comment by dabrain34** [comment]
Should be fix with last pull request #5
