### ISSUE TITLE
unable to build on ubuntu 20

### ISSUE THREAD

**Issue by sfahadshahzad** [virinext/pipeviz#60]
Hi,

I am getting error when building from source.

QMAKEFEATURES=. qmake pipeviz.pro

Project ERROR: Unknown module(s) in QT: core gui widgets xml

Fahad

**Comment by dabrain34** [comment]
You need to install the distributions package for Qt such `apt install libqt5widgets5`

**Comment by zdanek** [comment]
I just built it on Ubuntu 20.04, QT 5.15. I assume you checked out into `pipeviz` directory.
```
cd pipeviz
mkdir build
cd build
QMAKEFEATURES=. qmake ../pipeviz.pro
make -j 8
./pipeviz
```
